#mybatis
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
     #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
     #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
     #刷新mapper 调试神器
    refresh-mapper: true
     #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-parser-cache: true
  configuration:
   #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false


#热部署
devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 8080
  restart:
    enabled: true #是否支持热部署
